name: Run End-to-End Tests
on:
  workflow_call:
  push:
    branches:
      - release/*

jobs:
  trigger-tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow End-to-End
        run: |
            repo=${{ github.repository }}
            file_path=$(echo "workflow_tests_e2e")
            curl -X POST \
              -H "Authorization: token ${{ secrets.ENV_PAT  }}" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/alexfariakof/despesas-e2e-tests/dispatches \
              -d "{\"event_type\":\"trigger-python-plyawright-e2e-tests\", \"client_payload\": {\"unit\": false, \"integration\": true, \"father_workflow_id\": \"${{ github.run_id }}\", \"path\": \"$file_path\", \"repo\": \"$repo\" }}"
        continue-on-error: false

      - name: Wait Workflow End-to-End Initialize And Update File triggered-workflow-id
        run: sleep 15

      - name: Wait for Triggered Workflow Test e2e Run
        run: |
            download_url="https://raw.githubusercontent.com/${{ github.repository }}/attachments/triggered-workflow-id-${{ github.run_id }}"
            curl -o triggered-workflow-id -L "$download_url"
            triggered_workflow_id=$(cat triggered-workflow-id)
            echo "Triggered Workflow ID: $triggered_workflow_id"

            response=""
            status=""

            while true; do
              response=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ENV_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/alexfariakof/despesas-frontend-angular-tests-e2e/actions/runs/$triggered_workflow_id")

                status=$(echo $response | jq -r '.status')
                echo "Current status: $status"

                if [ "$status" == "queued" ] || [ "$status" == "in_progress" ]; then
                  sleep 20
                else
                  break
                fi
            done

            conclusion=$(echo $response | jq -r '.conclusion')
            echo "Conclusion: $conclusion"

            if [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
              echo "workflow_status=${{ job.status }}" >> $GITHUB_OUTPUT
            else
              echo "workflow_status=failure" >> $GITHUB_OUTPUT
              exit 1
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

